name: (UAT) Migrations - run

on:
  workflow_dispatch:
    inputs:
      MYSQL_HOST:
        required: true
        type: string
      IMAGE_VERSION:
        default: "latest"

jobs:
  run_migrations:
    runs-on: ubuntu-24.04
    environment: uat
    steps:
      - name: Run Migrations
        uses: ./.github/actions/run-migrations-uat
        with:
          MYSQL_HOST: ${{ inputs.MYSQL_HOST }}
          IMAGE_VERSION: ${{ inputs.DB_IMAGE_VERSION }}
          RELEASE_AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_ACCESS_KEY_ID }}
          RELEASE_AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_SECRET_ACCESS_KEY }}
          RELEASE_AWS_REGION: ${{ vars.RELEASE_AWS_REGION }}
          RELEASE_MR_IMAGE_REPOSITORY: ${{ vars.RELEASE_MR_IMAGE_REPOSITORY }}